[workspace]
members = ["src-tauri"]

[package]
name = "demo-app-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.21.0", features = ["csr"] }

wasm-bindgen = "0.2.92"
js-sys = "0.3.69"
