[workspace]
members = ["./crates/*", "./webapp"]
package.version = "0.1.0"
package.edition = "2021"

[package]
name = "node-network"
version.workspace = true
edition.workspace = true

[dependencies]
tool-code = { path = "./crates/tool-code" }
netprotocol = { path = "./crates/netprotocol" }

eyre = "0.6.12"               #错误处理
tracing = "0.1.40"            #日志生产者
tracing-subscriber = "0.3.18" #日志消费者
