[workspace]
members = ["./web", "./web/app"]
package.version = "0.1.0"
package.edition = "2021"

[package]
name = "node-network"
version.workspace = true
edition.workspace = true

[dependencies]
quinn = { version = "0.11.2", features = ["ring"] } #QUIC协议
rustls = "0.23.10"                                  #TLS加密
rcgen = "0.13.1"                                    #自签名X.509证书生成
uuid = { version = "1.9.1", features = ["v4"] }     #通用唯一标识符

serde = { version = "1.0.203", features = ["derive"] } #编解码特性
rmp-serde = "1.3.0"                                    #MessagePack编解码
