[workspace]
members = ["src-tauri"]

[package]
name = "demo-app-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.21.0", features = ["csr"] }

wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"
js-sys = "0.3.69"

serde = { version = "1.0.203", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
