[package]
name = "app"
version = "0.0.0"
edition = "2021"

[lib]
name = "app_"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.4", features = [] }

[dependencies]
tauri = { version = "2.2.0", features = [] }
tauri-plugin-shell = "2.2.0"
serde_json = "1.0.134"
tauri-plugin-prevent-default = "1.0.1"
