[package]
name = "app"
version = "0.0.0"
edition = "2021"

[lib]
name = "app_"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.3", features = [] }

[dependencies]
tauri = { version = "2.1.1", features = [] }
tauri-plugin-shell = "2.0.2"
serde_json = "1.0.133"

anyhow = "1.0.93"                                   #错误处理
tokio = { version = "1.41.1", features = ["full"] } #异步运行时
