[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
base64 = "0.22.1"
x509-parser = "0.16.0"
quinn = "0.11.6"
log = "0.4.25"
flexi_logger = "0.29.8"
nu-ansi-term = "0.50.1"
borsh = "1.5.4"
tauri-plugin-log = "2.2.0"
chrono = "0.4.39"
