[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"

x509-parser = "0.16.0"
quinn = "0.11.6"

serde = { version = "1.0.217", features = ["derive"] }
ciborium = "0.2.2"
base64 = "0.22.1"
