[package]
name = "cert-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"

clap = { version = "4.5.23", features = ["derive"] }
rcgen = "0.13.2"
uuid = { version = "1.11.0", features = ["v4"] }
